### PR TITLE
add TypeScript type definitions

### PR DESCRIPTION
**Pull request by JCMais**
This should greatly improve the developer experience.

There are a few TODOs in there, but nothing major.

Closes https://github.com/webflow/js-webflow-api/issues/20

### CODE REVIEW

**Comment by jlambright** [comment]
Is this even being considered?

**Comment by Jeandcc** [comment]
Come on guys.... @sansmischevia or @n-johnson  , can you guys merge this?

**Comment by namuol** [comment]
@JCMais Thank you so much for this enhancement! I'm going to merge this PR as-is, but we may need to spend a little time reviewing the code before we publish to NPM. I'll be sure to follow up here once this has been published, hopefully within the next 24h.

Also thanks to everyone who has patiently waited for us to follow up here. Better late than never! 😅

**Comment by namuol** [comment]
Update: Version `0.5.4` is [now live on NPM](https://www.npmjs.com/package/webflow-api). You should be able to update your package to get TypeScript coverage now. Thank you for your patience!

**Comment by Jeandcc** [comment]
Awesome stuff! Should we expect more movement on this SDK moving forward?

**Comment by JCMais** [comment]
Thanks for getting this merged @namuol

**Comment by mehdi-loup** [comment]
@namuol Just installed the package but the `index.d.ts` is missing

**Comment by mehdi-loup** [comment]
not sure if that's intentional but the types are not included in the package. Might want to add them [here](https://github.com/webflow/js-webflow-api/blob/master/package.json#L13-L18)

**Comment by 5amhoward** [comment]
Seems that the types are missing from NPM, I guess this is the reason as @mehdi-loup suggested?

**Pull request merged**
