### PR TITLE
Add patchItem call

### PR DESCRIPTION
**Pull request by vivanwin**

### CODE REVIEW

**Comment by samheutmaker** [comment]
@n-johnson what's the status on this?

**Comment by samheutmaker** [comment]
@jacobwgillespie pinging you for input on this.

**Comment by jacobwgillespie** [comment]
> @jacobwgillespie pinging you for input on this.

Thanks for the ping, however I'm no longer working at Webflow. 🙂

**Comment by samheutmaker** [comment]
@jacobwgillespie darn, do you know anyone who might be able to take this over? It would be fantastic if you could ping them in this thread :)

**Comment by jacobwgillespie** [comment]
> do you know anyone who might be able to take this over?

I don't, sorry!

**Comment by n-johnson** [comment]
:wave: Hey @jacobwgillespie ! We will get this merged and a new version of the package released ASAP.

**Comment by samheutmaker** [comment]
@n-johnson 👍 Awesome guys, thanks.

**Comment by kyleshevlin** [comment]
Closes #11

**Pull request merged**
