### PR TITLE
Fix issue with customFields not being inserted into createItem()

### PR DESCRIPTION
**Pull request by ivarvermeulen**
I know this PR might be useless as the files I fixed should be generated from your API, but for me this was the only option to fix the issue. I've added the prepare script in the package.json in order to be able to install the package from my github fork, so running `npm install https://github.com/The-Any-Thing/js-webflow-api` as a temp fix

### CODE REVIEW

**Comment by dsinghvi** [comment]
👋 @ivarvermeulen We've just enabled stronger GitHub monitoring to track the issues. You'll see us being more responsive to these sorts of issues!

**Comment by travisjbeck** [comment]
man, i've been scratching my head trying to figure out why fieldData is typed like that in the API, how does anyone use this as is?  Thanks.

**Comment by RichardSPrins** [comment]
> man, i've been scratching my head trying to figure out why fieldData is typed like that in the API, how does anyone use this as is? Thanks.

I am wondering the same, it doesn't allow for any custom fields, which makes the SDK virtually useless in this state, but it seems the HTTP endpoints are also failing on validation for custom fields as well, even after manually adding them in the CMS UI.

**Comment by zplata** [comment]
Hey @ivarvermeulen  @travisjbeck - we just shipped `v2.4.0` which should allow extra data in `fieldData` to be set. Thank you @ivarvermeulen for contributions on this PR. As you've noticed, most of the SDK is automatically generated from our OpenAPI spec, so closing this for now, as it was addressed in the most recent release.

**Pull request closed without merging**
